//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Batt_Return
    {   
        public System.DateTime return_date { get; set; }
        public Nullable<System.DateTime> purchase_date { get; set; }
        public short emp_id { get; set; }
        public short cust_id { get; set; }
        public string battery_maker { get; set; }
        public short height_id { get; set; }
        public short terminal_id { get; set; }
        public short size_id { get; set; }
        public Nullable<short> batt_quant_return { get; set; }
        public short supplier_id { get; set; }
        public short batt_return_id { get; set; }
    
        public virtual Battery Battery { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Height Height { get; set; }
        public virtual Size Size { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Terminal Terminal { get; set; }
    }
}
