//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battery
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Battery()
        {
            this.Batt_Return = new HashSet<Batt_Return>();
        }
    
        public System.DateTime Date { get; set; }
        public short supplier_id { get; set; }
        public short size_id { get; set; }
        public short terminal_id { get; set; }
        public short height_id { get; set; }
        public short Batt_quantity { get; set; }
        public decimal Batt_Unit_Price { get; set; }
        public Nullable<decimal> Total_Price { get; set; }
        public string Batt_description { get; set; }
        public short batt_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batt_Return> Batt_Return { get; set; }
        public virtual Height Height { get; set; }
        public virtual Size Size { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Terminal Terminal { get; set; }
    }
}
