//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Batt_Return = new HashSet<Batt_Return>();
            this.batt_sales_record = new HashSet<batt_sales_record>();
            this.Employee_Login = new HashSet<Employee_Login>();
            this.Rim_Return = new HashSet<Rim_Return>();
            this.Rim_Sale_Record = new HashSet<Rim_Sale_Record>();
            this.Sales_Record = new HashSet<Sales_Record>();
        }
    
        public string emp_name { get; set; }
        public string emp_phone_no { get; set; }
        public string emp_address { get; set; }
        public string emp_city { get; set; }
        public string emp_state { get; set; }
        public string emp_country { get; set; }
        public short emp_id { get; set; }
        public System.DateTime Date_Started { get; set; }
        public Nullable<System.DateTime> Date_Ended { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batt_Return> Batt_Return { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<batt_sales_record> batt_sales_record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee_Login> Employee_Login { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rim_Return> Rim_Return { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rim_Sale_Record> Rim_Sale_Record { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales_Record> Sales_Record { get; set; }
    }
}
