//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rim()
        {
            this.Rim_Return = new HashSet<Rim_Return>();
            this.Rim_Sale_Record = new HashSet<Rim_Sale_Record>();
        }
    
        public System.DateTime Date { get; set; }
        public short size_id { get; set; }
        public short type_id { get; set; }
        public short hub_id { get; set; }
        public short peg_id { get; set; }
        public string Car_rims { get; set; }
        public short Rim_quantity { get; set; }
        public decimal Rim_unit_price { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string Rim_description { get; set; }
        public short rim_id { get; set; }
    
        public virtual Rim_hub Rim_hub { get; set; }
        public virtual Rim_Peg Rim_Peg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rim_Return> Rim_Return { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rim_Sale_Record> Rim_Sale_Record { get; set; }
        public virtual Rim_size Rim_size { get; set; }
        public virtual Rim_Type Rim_Type { get; set; }
    }
}
