//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rim_Return
    {
        public short cust_id { get; set; }
        public short emp_id { get; set; }
        public short hub_id { get; set; }
        public short peg_id { get; set; }
        public short size_id { get; set; }
        public short type_id { get; set; }
        public System.DateTime rim_return_date { get; set; }
        public Nullable<short> rim_quant_return { get; set; }
        public Nullable<System.DateTime> rim_purchase_date { get; set; }
        public short rim_return_id { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Rim_hub Rim_hub { get; set; }
        public virtual Rim_Peg Rim_Peg { get; set; }
        public virtual Rim_size Rim_size { get; set; }
        public virtual Rim_Type Rim_Type { get; set; }
        public virtual Rim Rim { get; set; }
    }
}
