//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Salesapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Record
    {
        public short prod_id { get; set; }
        public short cust_id { get; set; }
        public short emp_id { get; set; }
        public short unit_purchase { get; set; }
        public double unit_price { get; set; }
        public double total_price { get; set; }
        public short sales_id { get; set; }
        public System.DateTime Dates { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Product Product { get; set; }
    }
}
